import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import {
  CardCollectionBrowser,
  chooseCardInstanceId,
  groupCardCollection,
  shouldCloseCardCollection,
  toggleCardSelection,
} from "./CardCollectionBrowser";
import type { CardInstance } from "../domain/models";

const cards: readonly CardInstance[] = [
  { cardId: "frontend-3", instanceId: "frontend-second" },
  { cardId: "backend-3", instanceId: "backend-first" },
  { cardId: "frontend-3", instanceId: "frontend-first" },
];

describe("CardCollectionBrowser", () => {
  it("groups duplicate definitions and sorts by card name instead of pile order", () => {
    expect(groupCardCollection(cards)).toEqual([
      { cardId: "backend-3", count: 1 },
      { cardId: "frontend-3", count: 2 },
    ]);
  });

  it("does not expose hidden instance order in inspect markup", () => {
    const markup = renderToStaticMarkup(
      <CardCollectionBrowser cards={cards} title="Draw" orderHidden onClose={() => undefined} />,
    );

    expect(markup).toContain("Order hidden");
    expect(markup).toContain("×2");
    expect(markup).not.toContain("frontend-first");
    expect(markup).not.toContain("frontend-second");
  });

  it("toggles one chosen definition and resolves one eligible instance", () => {
    expect(toggleCardSelection(undefined, "frontend-3")).toBe("frontend-3");
    expect(toggleCardSelection("frontend-3", "frontend-3")).toBeUndefined();
    expect(toggleCardSelection(undefined, "frontend-3", false)).toBeUndefined();
    expect(
      chooseCardInstanceId(cards, "frontend-3", (instance) =>
        instance.instanceId.endsWith("first"),
      ),
    ).toBe("frontend-first");
  });

  it("maps Escape to the close action", () => {
    expect(shouldCloseCardCollection("Escape")).toBe(true);
    expect(shouldCloseCardCollection("Enter")).toBe(false);
  });

  it("renders removal as a modal single-select flow", () => {
    const markup = renderToStaticMarkup(
      <CardCollectionBrowser
        cards={cards}
        title="Remove"
        mode="choose-one"
        confirmLabel="Remove"
        onClose={() => undefined}
        onChoose={() => undefined}
      />,
    );

    expect(markup).toContain("<dialog");
    expect(markup).toContain('aria-modal="true"');
    expect(markup).toContain('aria-pressed="false"');
    expect(markup).toContain("Remove");
  });

  it("uses the full card's output language for compact tactics", () => {
    const markup = renderToStaticMarkup(
      <CardCollectionBrowser
        cards={[
          { cardId: "standup-cover", instanceId: "block" },
          { cardId: "feature-flag", instanceId: "stun" },
        ]}
        title="Refactor"
        onClose={() => undefined}
      />,
    );

    expect(markup).toContain("Standup Cover");
    expect(markup).toContain("Feature Flag");
    expect(markup).toContain("<small>Block</small>");
    expect(markup).toContain("<small>Cancel</small>");
    expect(markup).not.toContain("<small>Status</small>");
    expect(markup).toContain("Gain 3 Block.");
    expect(markup).toContain("Cancel one Task&#x27;s End Day effect.");
  });

  it("keeps Generated provenance and Exhaust lifecycle visible in pile inspection", () => {
    const markup = renderToStaticMarkup(
      <CardCollectionBrowser
        cards={[
          {
            cardId: "quick-fix",
            instanceId: "generated-1",
            generated: true,
            generatedBy: {
              sourceCardId: "new-model-dropped",
              sourceInstanceId: "source-1",
              day: 2,
            },
            exhausted: { day: 2, cause: "played" },
          },
        ]}
        title="Exhaust"
        onClose={() => undefined}
      />,
    );

    expect(markup).toContain("Generated");
    expect(markup).toContain("Exhausted");
    expect(markup).toContain("generated by new-model-dropped on Day 2");
    expect(markup).toContain("exhausted on Day 2");
  });
});
