import elspethIdle from "../../assets/characters/elspeth-idle-v1.webp";
import elspethSuccess from "../../assets/characters/elspeth-success-v1.webp";
import elspethThinking from "../../assets/characters/elspeth-thinking-v1.webp";

export const elspethContent = {
  developer: {
    id: "elspeth",
    name: "Elspeth",
    role: "Team Lead",
    passiveName: "Healthy Pace",
    passiveRules: "Whenever you play a card with the Flexible tag, gain 2 Block.",
    startingCardId: "make-space",
    accent: "oklch(0.62 0.16 315)",
    art: {
      idle: elspethIdle,
      thinking: elspethThinking,
      success: elspethSuccess,
    },
  },
  startingCard: {
    id: "make-space",
    ownerId: "elspeth",
    name: "Make Space",
    cost: 1,
    kind: "work",
    discipline: "flexible",
    amount: 3,
    workKind: "verified",
    block: 3,
    display: { value: "3", label: "Any", rules: "Verified. Block 3." },
    rules: "Any 3. Verified. Gain 3 Block.",
    tags: ["character", "defense", "flexible"],
  },
  rewardCards: [
    {
      id: "psychological-safety",
      ownerId: "elspeth",
      name: "Psychological Safety",
      cost: 1,
      kind: "status",
      amount: 0,
      cycleFlexibleBlockBonus: 2,
      exhaust: true,
      display: { value: "+2", label: "Flexible Block", rules: "This Cycle. Exhaust." },
      rarity: "normal",
      rules: "Flexible cards gain 2 additional Block this Cycle. Exhaust.",
      tags: ["character", "defense", "exhaust", "reward", "status"],
    },
    {
      id: "check-in",
      ownerId: "elspeth",
      name: "Check In",
      cost: 1,
      kind: "tactic",
      amount: 0,
      generatedCards: [
        { cardId: "snippet", count: 1 },
        { cardId: "checklist", count: 1 },
      ],
      display: { value: "2", label: "Cards", rules: "Snippet + Checklist." },
      rarity: "normal",
      rules: "Generate a Snippet and a Checklist.",
      tags: ["character", "reward"],
    },
    {
      id: "air-cover",
      ownerId: "elspeth",
      name: "Air Cover",
      cost: 1,
      kind: "tactic",
      amount: 0,
      blockPerOpenTask: 3,
      display: { value: "×3", label: "Block", rules: "Per open Task." },
      rarity: "normal",
      rules: "Gain 3 Block for every open Task.",
      tags: ["character", "defense", "reward"],
    },
    {
      id: "room-to-breathe",
      ownerId: "elspeth",
      name: "Room to Breathe",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 3,
      workKind: "verified",
      cardsDrawnIfBlockCoversIncoming: 2,
      display: { value: "3", label: "Any", rules: "Verified. Safe: Draw 2." },
      rarity: "normal",
      rules: "Any 3. Verified. If Block covers all incoming Morale, draw 2.",
      tags: ["character", "defense", "flexible", "reward"],
    },
    {
      id: "healthy-guardrails",
      ownerId: "elspeth",
      name: "Healthy Guardrails",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 1,
      workKind: "verified",
      automation: { kind: "install", power: 0, blockPower: 2 },
      triggerAutomationAfterInstall: ["guard"],
      display: { value: "1", label: "Any", rules: "Verified. Guard 2, trigger." },
      rarity: "normal",
      rules: "Any 1. Verified. Install Guard 2, then trigger it.",
      tags: ["automation", "character", "defense", "flexible", "reward"],
    },
    {
      id: "sustainable-pace",
      ownerId: "elspeth",
      name: "Sustainable Pace",
      cost: 1,
      kind: "tactic",
      amount: 0,
      block: 10,
      focusGained: 3,
      cardsDrawn: 3,
      exhaust: true,
      display: { value: "+10", label: "Block", rules: "+3 Focus. Draw 3. Exhaust." },
      rarity: "rare",
      rules: "Gain 10 Block, 3 Focus, and draw 3. Exhaust.",
      tags: ["character", "defense", "exhaust", "rare", "reward"],
    },
  ],
} as const;
