import kirstenIdle from "../../assets/characters/kirsten-idle-v2.webp";
import kirstenSuccess from "../../assets/characters/kirsten-success-v1.webp";
import kirstenThinking from "../../assets/characters/kirsten-thinking-v1.webp";
import type { CharacterContent } from "./types";

export const kirstenContent = {
  developer: {
    id: "kirsten",
    name: "Kirsten",
    role: "Developer",
    passiveName: "Learning by Doing",
    passiveRules: "Generated cards gain +1 to each Work, Review, and Block amount.",
    startingCardId: "give-it-a-go",
    accent: "oklch(0.7 0.17 155)",
    art: {
      idle: kirstenIdle,
      thinking: kirstenThinking,
      success: kirstenSuccess,
    },
  },
  startingCard: {
    id: "give-it-a-go",
    ownerId: "kirsten",
    name: "Give It a Go",
    cost: 1,
    kind: "tactic",
    amount: 0,
    generatedCards: [
      { cardId: "snippet", count: 1 },
      { cardId: "checklist", count: 1 },
    ],
    display: { value: "2", label: "Generate", rules: "Snippet + Checklist." },
    rules: "Generate a Snippet and a Checklist.",
    tags: ["character"],
  },
  rewardCards: [
    {
      id: "ask-a-good-question",
      ownerId: "kirsten",
      name: "Ask a Good Question",
      cost: 1,
      kind: "tactic",
      amount: 0,
      generatedCards: { cardId: "comment", count: 2 },
      display: { value: "2", label: "Comments" },
      rules: "Generate 2 Comments.",
      tags: ["character", "reward"],
      rarity: "normal",
    },
    {
      id: "try-a-different-way",
      ownerId: "kirsten",
      name: "Try a Different Way",
      cost: 1,
      kind: "tactic",
      amount: 0,
      generatedCards: [
        { cardId: "quick-fix", count: 1 },
        { cardId: "snippet", count: 1 },
      ],
      display: { value: "2", label: "Generate", rules: "Quick Fix + Snippet." },
      rules: "Generate a Quick Fix and a Snippet.",
      tags: ["character", "reward"],
      rarity: "normal",
    },
    {
      id: "second-attempt",
      ownerId: "kirsten",
      name: "Second Attempt",
      cost: 0,
      kind: "tactic",
      amount: 0,
      retrieveGeneratedFromExhaust: true,
      exhaust: true,
      display: { value: "↩", label: "Generated", rules: "Return from Exhaust. Exhaust." },
      rules: "Return a Generated card from Exhaust to your hand. Exhaust.",
      tags: ["character", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "it-all-adds-up",
      ownerId: "kirsten",
      name: "It All Adds Up",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 0,
      amountPerGeneratedCardPlayed: 1,
      workKind: "verified",
      display: { value: "×1", label: "Any", rules: "Per Generated play today." },
      rules: "Any 1 Verified for every Generated card played before this card today.",
      tags: ["character", "flexible", "reward"],
      rarity: "normal",
    },
    {
      id: "on-a-roll",
      ownerId: "kirsten",
      name: "On a Roll",
      cost: 0,
      kind: "tactic",
      amount: 0,
      focusPerGeneratedCardsPlayed: 2,
      exhaust: true,
      display: { value: "+1", label: "Focus", rules: "Per 2 Generated plays. Exhaust." },
      rules: "Gain 1 Focus for every 2 Generated cards played before this card today. Exhaust.",
      tags: ["character", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "fast-learner",
      ownerId: "kirsten",
      name: "Fast Learner",
      cost: 1,
      kind: "tactic",
      amount: 0,
      generateLastNonGeneratedCopy: true,
      exhaust: true,
      display: { value: "1", label: "Copy", rules: "Costs 0. Generated. Exhaust." },
      rules: "Generate a zero-cost copy of the last non-Generated card played this Day. Exhaust.",
      tags: ["character", "exhaust", "rare", "reward"],
      rarity: "rare",
    },
  ],
} as const satisfies CharacterContent<"kirsten">;
