import leviIdle from "../../assets/characters/levi-idle-v2.webp";
import leviSuccess from "../../assets/characters/levi-success-v1.webp";
import leviThinking from "../../assets/characters/levi-thinking-v1.webp";
import type { CharacterContent } from "./types";

export const leviContent = {
  developer: {
    id: "levi",
    name: "Levi",
    role: "Web Developer",
    passiveName: "Momentum",
    passiveRules: "Targeted Work gains Work equal to the resulting Chain.",
    startingCardId: "heads-down",
    accent: "oklch(0.62 0.17 205)",
    art: { idle: leviIdle, thinking: leviThinking, success: leviSuccess },
  },
  startingCard: {
    id: "heads-down",
    ownerId: "levi",
    name: "Heads Down",
    cost: 1,
    kind: "work",
    discipline: "frontend",
    amount: 3,
    workKind: "verified",
    additionalChain: 1,
    display: { value: "3", label: "Frontend", rules: "Verified. Chain +1 extra." },
    rules: "Frontend 3. Verified. Advance Chain one additional time.",
    tags: ["character"],
  },
  rewardCards: [
    {
      id: "tiny-commit",
      ownerId: "levi",
      name: "Tiny Commit",
      cost: 0,
      kind: "work",
      discipline: "frontend",
      amount: 1,
      workKind: "verified",
      exhaust: true,
      rules: "Frontend 1. Verified. Exhaust.",
      tags: ["character", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "keep-the-thread",
      ownerId: "levi",
      name: "Keep the Thread",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 2,
      workKind: "verified",
      drawIfContinuesChain: 1,
      display: { value: "2", label: "Any", rules: "Continue Chain: Draw 1." },
      rules: "Any 2. Verified. If it continues an existing Chain, draw 1.",
      tags: ["character", "flexible", "reward"],
      rarity: "normal",
    },
    {
      id: "stacked-prs",
      ownerId: "levi",
      name: "Stacked PRs",
      cost: 1,
      kind: "work",
      discipline: "frontend",
      amount: 2,
      workKind: "verified",
      additionalChain: 2,
      display: { value: "2", label: "Frontend", rules: "Verified. Chain +2 extra." },
      rules: "Frontend 2. Verified. Advance Chain two additional times.",
      tags: ["character", "reward"],
      rarity: "normal",
    },
    {
      id: "do-not-disturb",
      ownerId: "levi",
      name: "Do Not Disturb",
      cost: 1,
      kind: "tactic",
      amount: 0,
      blockPerChain: 2,
      exhaust: true,
      display: { value: "×2", label: "Block", rules: "Per Chain. Exhaust." },
      rules: "Gain 2 Block for each Chain. Exhaust.",
      tags: ["character", "defense", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "context-loaded",
      ownerId: "levi",
      name: "Context Loaded",
      cost: 1,
      kind: "tactic",
      amount: 0,
      generatedCardsPerChain: { cardId: "snippet", divisor: 2 },
      exhaust: true,
      display: { value: "÷2", label: "Snippets", rules: "From Chain. Exhaust." },
      rules: "Generate one Snippet for every 2 Chain. Exhaust.",
      tags: ["character", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "flow-state",
      ownerId: "levi",
      name: "Flow State",
      cost: 1,
      kind: "tactic",
      amount: 0,
      doubleChain: true,
      transferChainThisDay: true,
      exhaust: true,
      display: { value: "×2", label: "Chain", rules: "Moves across Tasks this Day. Exhaust." },
      rules: "Double Chain. It no longer resets when targeting a different Task this Day. Exhaust.",
      tags: ["character", "exhaust", "rare", "reward"],
      rarity: "rare",
    },
  ],
} as const satisfies CharacterContent<"levi">;
