import madiDelighted from "../../assets/characters/madi-delighted-v1.webp";
import madiMaster from "../../assets/characters/madi-master-v1.webp";
import madiProcessing from "../../assets/characters/madi-processing-v1.webp";
import type { CharacterContent } from "./types";

export const madiContent = {
  developer: {
    id: "madi",
    name: "Madi",
    role: "Tinkerer",
    passiveName: "Custom Setup",
    passiveRules: "Every AI Assisted card installs Script 1 on its target.",
    startingCardId: "agent-swarm",
    accent: "oklch(0.64 0.2 343)",
    art: {
      idle: madiMaster,
      thinking: madiProcessing,
      success: madiDelighted,
    },
  },
  startingCard: {
    id: "agent-swarm",
    ownerId: "madi",
    name: "Agent Swarm",
    cost: 1,
    kind: "work",
    discipline: "backend",
    amount: 5,
    workKind: "unverified",
    rules: "Backend 5. Unverified. AI Assisted.",
    tags: ["character", "ai-assisted"],
  },
  rewardCards: [
    {
      id: "yak-shave",
      ownerId: "madi",
      name: "Yak Shave",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 0,
      automation: { kind: "install", power: 2 },
      queuedDistractions: 1,
      display: { value: "+2", label: "Script", rules: "Next Day: 1 Distraction." },
      rarity: "normal",
      rules: "Install Script 2 on a requirement. Next Day: 1 Distraction.",
      tags: ["character", "automation", "flexible", "reward"],
    },
    {
      id: "custom-toolchain",
      ownerId: "madi",
      name: "Custom Toolchain",
      cost: 1,
      kind: "tactic",
      amount: 0,
      cycleWorkBonus: { tag: "ai-assisted", amount: 2 },
      exhaust: true,
      display: { value: "+2", label: "AI Work", rules: "This Cycle. Stacks. Exhaust." },
      rarity: "normal",
      rules: "AI Assisted Work gains +2 Work this Cycle. Exhaust.",
      tags: ["character", "automation", "exhaust", "reward"],
    },
    {
      id: "plan-it-out",
      ownerId: "madi",
      name: "Plan It Out",
      cost: 1,
      kind: "tactic",
      amount: 0,
      nextDayCardsDrawn: 3,
      exhaust: true,
      display: { value: "+3", label: "Next Draw", rules: "Next Day. Exhaust." },
      rarity: "normal",
      rules: "Draw 3 additional cards at the start of the next Day. Exhaust.",
      tags: ["character", "exhaust", "reward"],
    },
    {
      id: "write-the-rfc",
      ownerId: "madi",
      name: "Write the RFC",
      cost: 1,
      kind: "review",
      amount: 3,
      scriptPowerPerIncompleteRequirement: 1,
      display: { value: "3", label: "Verify", rules: "Then Script +1 on incomplete bars." },
      rarity: "normal",
      rules: "Verify 3, then install Script 1 on each incomplete requirement on that Task.",
      tags: ["character", "automation", "review", "reward"],
    },
    {
      id: "agentic-loop",
      ownerId: "madi",
      name: "Agentic Loop",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 2,
      workKind: "unverified",
      triggerTargetScriptAfterWork: true,
      display: { value: "2", label: "Any", rules: "Unverified. AI Assisted. Trigger Script." },
      rarity: "normal",
      rules: "Any 2. Unverified. AI Assisted. Then trigger the target Script.",
      tags: ["character", "ai-assisted", "flexible", "reward"],
    },
    {
      id: "parallel-agents",
      ownerId: "madi",
      name: "Parallel Agents",
      cost: 1,
      kind: "tactic",
      amount: 0,
      generatedCards: { cardId: "sub-agent", count: 3 },
      techDebtAdded: 1,
      exhaust: true,
      display: { value: "3", label: "Sub-Agents", rules: "+1 Tech Debt. Exhaust." },
      rarity: "rare",
      rules: "Generate 3 Sub-Agents. Gain 1 Tech Debt. Exhaust.",
      tags: ["character", "ai-assisted", "exhaust", "rare", "reward"],
    },
  ],
  generatedCards: [
    {
      id: "sub-agent",
      name: "Sub-Agent",
      cost: 0,
      kind: "work",
      discipline: "flexible",
      amount: 1,
      workKind: "unverified",
      triggerTargetScriptAfterWork: true,
      exhaust: true,
      rules: "Any 1. Unverified. AI Assisted. Then trigger the target Script. Exhaust.",
      tags: ["character", "ai-assisted", "exhaust", "flexible", "generated"],
    },
  ],
} as const satisfies CharacterContent<"madi">;
