import mattIdle from "../../assets/characters/matt-idle-v2.webp";
import mattSuccess from "../../assets/characters/matt-success-v1.webp";
import mattThinking from "../../assets/characters/matt-thinking-v1.webp";

/** See Seb's catalogue note: shared typing is intentionally added by the integration pass. */
export const mattContent = {
  developer: {
    id: "matt",
    name: "Matt",
    role: "Design Engineer",
    passiveName: "Finishing Touches",
    passiveRules: "Overflow from Verified Work becomes real Review on that Task.",
    startingCardId: "delight-moment",
    accent: "oklch(0.64 0.2 25)",
    art: {
      idle: mattIdle,
      thinking: mattThinking,
      success: mattSuccess,
    },
  },
  startingCard: {
    id: "delight-moment",
    ownerId: "matt",
    name: "Delight Moment",
    cost: 1,
    kind: "work",
    discipline: "frontend",
    amount: 4,
    workKind: "verified",
    cardsDrawnOnRequirementComplete: 1,
    display: { value: "4", label: "Frontend", rules: "Verified. Complete: draw 1." },
    rules: "Frontend 4. Verified. Draw 1 if it completes the requirement.",
    tags: ["character"],
  },
  rewardCards: [
    {
      id: "one-more-pass",
      ownerId: "matt",
      name: "One More Pass",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 5,
      workKind: "verified",
      maxTargetRemaining: 3,
      exhaust: true,
      display: { value: "5", label: "Any", rules: "3 or less remaining. Exhaust." },
      rules: "Any 5. Verified. Only target 3 or less Work remaining. Exhaust.",
      tags: ["character", "exhaust", "flexible", "reward"],
      rarity: "normal",
    },
    {
      id: "polish-budget",
      ownerId: "matt",
      name: "Polish Budget",
      cost: 1,
      kind: "tactic",
      amount: 0,
      blockPerFinishingTouchesReview: 1,
      exhaust: true,
      display: { value: "1:1", label: "Review → Block", rules: "This Day. Exhaust." },
      rules: "This Day, gain Block equal to Review from Finishing Touches. Exhaust.",
      tags: ["character", "defense", "exhaust", "review", "reward"],
      rarity: "normal",
    },
    {
      id: "no-rough-edges",
      ownerId: "matt",
      name: "No Rough Edges",
      cost: 1,
      kind: "review",
      amount: 5,
      focusIfTaskFullyVerified: 1,
      cardsDrawnIfTaskFullyVerified: 1,
      display: { value: "5", label: "Verify", rules: "Clean: +1 Focus, draw 1." },
      rules: "Verify 5. If no Unverified Work remains, gain 1 Focus and draw 1.",
      tags: ["character", "review", "reward"],
      rarity: "normal",
    },
    {
      id: "delight-budget",
      ownerId: "matt",
      name: "Delight Budget",
      cost: 1,
      kind: "tactic",
      amount: 0,
      blockPerCompletedRequirement: 3,
      display: { value: "3", label: "Block / Complete", rules: "Open Tasks." },
      rules: "Gain 3 Block for every completed requirement on open Tasks.",
      tags: ["character", "defense", "reward"],
      rarity: "normal",
    },
    {
      id: "microinteraction",
      ownerId: "matt",
      name: "Microinteraction",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 2,
      workKind: "verified",
      spilloverVerifiedOnCompletion: 2,
      display: { value: "2+2", label: "Any", rules: "Complete: spill 2 on this Task." },
      rules: "Any 2. Verified. On completion, add 2 Verified Work to the least remaining bar.",
      tags: ["character", "flexible", "reward"],
      rarity: "normal",
    },
    {
      id: "pixel-perfect",
      ownerId: "matt",
      name: "Pixel Perfect",
      cost: 1,
      kind: "work",
      discipline: "frontend",
      amount: 10,
      workKind: "verified",
      finishingTouchesEveryTask: true,
      cardsDrawnPerTaskCleaned: 1,
      exhaust: true,
      display: { value: "10", label: "Frontend", rules: "Overflow Reviews every Task." },
      rules: "Frontend 10. Overflow Reviews every open Task. Draw per Task cleaned. Exhaust.",
      tags: ["character", "exhaust", "rare", "reward"],
      rarity: "rare",
    },
  ],
} as const;
