import nickIdle from "../../assets/characters/nick-idle-v2.webp";
import nickSuccess from "../../assets/characters/nick-success-v1.webp";
import nickThinking from "../../assets/characters/nick-thinking-v1.webp";
import type { CharacterContent } from "./types";

export const nickContent = {
  developer: {
    id: "nick",
    name: "Nick",
    role: "CTO",
    passiveName: "Well Organised",
    passiveRules: "Whenever a card Exhausts, gain 1 Focus.",
    startingCardId: "clear-the-calendar",
    accent: "oklch(0.58 0.17 245)",
    art: { idle: nickIdle, thinking: nickThinking, success: nickSuccess },
  },
  startingCard: {
    id: "clear-the-calendar",
    ownerId: "nick",
    name: "Clear the Calendar",
    cost: 1,
    kind: "tactic",
    amount: 0,
    exhaustHandTarget: true,
    cardsDrawn: 2,
    display: { value: "2", label: "Draw", rules: "Exhaust another hand card." },
    rules: "Exhaust another card from your hand. Draw 2.",
    tags: ["character"],
  },
  rewardCards: [
    {
      id: "put-a-pin-in-it",
      ownerId: "nick",
      name: "Put a Pin in It",
      cost: 1,
      kind: "tactic",
      amount: 0,
      retainHandTarget: true,
      targetCostReduction: 1,
      exhaust: true,
      display: { value: "−1", label: "Cost", rules: "Retain chosen card. Exhaust." },
      rules: "Choose another card in hand. It Retains and costs 1 less until played. Exhaust.",
      tags: ["character", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "inbox-zero",
      ownerId: "nick",
      name: "Inbox Zero",
      cost: 0,
      kind: "tactic",
      amount: 0,
      exhaustHandTags: ["status"],
      exhaust: true,
      display: { value: "↻", label: "Statuses", rules: "Exhaust and replace. Exhaust." },
      rules: "Exhaust every Status card in hand, then draw that many cards. Exhaust.",
      tags: ["character", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "prioritise-ruthlessly",
      ownerId: "nick",
      name: "Prioritise Ruthlessly",
      cost: 1,
      kind: "tactic",
      amount: 0,
      cardsDrawn: 3,
      returnDrawnToTop: 2,
      exhaust: true,
      display: { value: "3", label: "Draw", rules: "Return 2 to Draw. Exhaust." },
      rules:
        "Draw 3, then put 2 cards from hand back on top of the draw pile in either order. Exhaust.",
      tags: ["character", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "timebox-it",
      ownerId: "nick",
      name: "Timebox It",
      cost: 1,
      kind: "tactic",
      amount: 0,
      blockPerExhaustedThisDay: 3,
      exhaust: true,
      display: { value: "×3", label: "Block", rules: "Per earlier Exhaust. Exhaust." },
      rules: "Gain 3 Block for every card Exhausted before this card today. Exhaust.",
      tags: ["character", "defense", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "deep-work",
      ownerId: "nick",
      name: "Deep Work",
      cost: 1,
      kind: "work",
      discipline: "backend",
      amount: 3,
      workPerRetainedCard: 2,
      workKind: "verified",
      display: { value: "3+", label: "Backend", rules: "+2 per Retained card." },
      rules: "Backend 3 Verified, plus 2 Work for every Retained card currently in hand.",
      tags: ["character", "reward"],
      rarity: "normal",
    },
    {
      id: "no-meetings",
      ownerId: "nick",
      name: "No Meetings",
      cost: 1,
      kind: "tactic",
      amount: 0,
      exhaustOtherHand: true,
      drawEntireDrawPile: true,
      exhaust: true,
      display: { value: "ALL", label: "Draw", rules: "Exhaust hand first. Exhaust." },
      rules: "Exhaust every other card in hand, then draw the rest of your draw pile. Exhaust.",
      tags: ["character", "exhaust", "rare", "reward"],
      rarity: "rare",
    },
  ],
} as const satisfies CharacterContent<"nick">;
