import odinMaster from "../../assets/characters/odin-master-v1.webp";
import odinSatisfied from "../../assets/characters/odin-satisfied-v1.webp";
import odinThinking from "../../assets/characters/odin-thinking-v1.webp";
import type { CharacterContent } from "./types";

export const odinContent = {
  developer: {
    id: "odin",
    name: "Odin",
    role: "Architect",
    passiveName: "I Have Concerns",
    passiveRules: "Every Review also Stuns that Task's intent.",
    startingCardId: "design-review",
    accent: "oklch(0.55 0.19 292)",
    art: {
      idle: odinMaster,
      thinking: odinThinking,
      success: odinSatisfied,
    },
  },
  startingCard: {
    id: "design-review",
    ownerId: "odin",
    name: "Design Review",
    cost: 1,
    kind: "review",
    amount: 5,
    rules: "Verify 5 on one Task.",
    tags: ["character", "review"],
  },
  rewardCards: [
    {
      id: "one-more-diagram",
      ownerId: "odin",
      name: "One More Diagram",
      cost: 1,
      kind: "review",
      amount: 6,
      retain: true,
      rules: "Verify 6. Retain.",
      tags: ["character", "review", "reward"],
      rarity: "normal",
    },
    {
      id: "strong-opinions-loosely-held",
      ownerId: "odin",
      name: "Strong Opinions, Loosely Held",
      cost: 1,
      kind: "tactic",
      amount: 0,
      dayReviewStunFocusBonus: 1,
      exhaust: true,
      display: {
        value: "+1",
        label: "Focus",
        rules: "Per Review Stun this Day. Stacks. Exhaust.",
      },
      rules: "This Day, whenever a Review Stuns an Intent, gain 1 Focus. Exhaust.",
      tags: ["character", "exhaust", "review", "reward"],
      rarity: "normal",
    },
    {
      id: "approved-with-comments",
      ownerId: "odin",
      name: "Approved With Comments",
      cost: 1,
      kind: "review",
      amount: 3,
      generatedCards: { cardId: "comment", count: 2 },
      display: { value: "3", label: "Verify", rules: "Generate 2 Comments." },
      rules: "Verify 3. Generate 2 Comments.",
      tags: ["character", "review", "reward"],
      rarity: "normal",
    },
    {
      id: "boring-technology",
      ownerId: "odin",
      name: "Boring Technology",
      cost: 1,
      kind: "work",
      discipline: "backend",
      amount: 4,
      workKind: "verified",
      bonusWorkIfTaskStunned: 3,
      display: { value: "4+3", label: "Backend", rules: "+3 Work vs Stunned Tasks." },
      rules: "Backend 4. Add 3 Work if the target Task's Intent is Stunned.",
      tags: ["character", "reward"],
      rarity: "normal",
    },
    {
      id: "manual-mode",
      ownerId: "odin",
      name: "Manual Mode",
      cost: 1,
      kind: "tactic",
      amount: 0,
      discardedHandTags: ["ai-assisted"],
      dayWorkBonus: { amount: 2, excludedTags: ["ai-assisted"] },
      exhaust: true,
      display: {
        value: "+2",
        label: "Non-AI Work",
        rules: "Discard AI Assisted hand. This Day. Exhaust.",
      },
      rules: "Discard every AI Assisted card in hand. Non-AI Work gains 2 Work this Day. Exhaust.",
      tags: ["character", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "architecture-review",
      ownerId: "odin",
      name: "Architecture Review",
      cost: 1,
      kind: "review",
      amount: 5,
      reviewEveryTask: true,
      cardsDrawnPerReviewStun: 1,
      exhaust: true,
      display: { value: "5", label: "Every Task", rules: "Draw 1 per Intent Stunned. Exhaust." },
      rules: "Verify 5 on every Task. Draw 1 for each Intent Stunned this way. Exhaust.",
      tags: ["character", "exhaust", "rare", "review", "reward"],
      rarity: "rare",
    },
  ],
  generatedCards: [
    {
      id: "comment",
      name: "Comment",
      cost: 0,
      kind: "review",
      amount: 1,
      exhaust: true,
      rules: "Verify 1. Exhaust.",
      tags: ["exhaust", "generated", "review"],
    },
  ],
} as const satisfies CharacterContent<"odin">;
