import paulMaster from "../../assets/characters/paul-master-v1.webp";
import paulShipped from "../../assets/characters/paul-shipped-v1.webp";
import paulThinking from "../../assets/characters/paul-thinking-v1.webp";
import type { CharacterContent } from "./types";

export const paulContent = {
  developer: {
    id: "paul",
    name: "Paul",
    role: "Prototyper",
    passiveName: "Move Fast",
    passiveRules: "Whenever a non-final Task ships, gain 1 Focus.",
    startingCardId: "vibe-code",
    accent: "oklch(0.68 0.19 31)",
    art: {
      idle: paulMaster,
      thinking: paulThinking,
      success: paulShipped,
    },
  },
  startingCard: {
    id: "vibe-code",
    ownerId: "paul",
    name: "Vibe Code",
    cost: 1,
    kind: "work",
    discipline: "flexible",
    amount: 4,
    workKind: "unverified",
    block: 2,
    display: { value: "4", label: "Any", rules: "Unverified. Block 2." },
    rules: "Any 4. Unverified. Gain 2 Block.",
    tags: ["character", "ai-assisted", "defense", "flexible"],
  },
  rewardCards: [
    {
      id: "spike-it",
      ownerId: "paul",
      name: "Spike It",
      cost: 0,
      kind: "work",
      discipline: "flexible",
      amount: 3,
      workKind: "unverified",
      exhaust: true,
      rarity: "normal",
      rules: "Any 3. Unverified. Exhaust.",
      tags: ["character", "ai-assisted", "exhaust", "flexible", "reward"],
    },
    {
      id: "side-quest",
      ownerId: "paul",
      name: "Side Quest",
      cost: 1,
      kind: "tactic",
      amount: 0,
      spawnSideQuest: true,
      exhaust: true,
      display: {
        value: "+1",
        label: "Prototype",
        rules: "Add 3-Work Task. Ship: Prototype +1.",
      },
      rarity: "normal",
      rules: "Add a 3-Work Task. Ship it: Prototype +1. Exhaust.",
      tags: ["character", "exhaust", "reward"],
    },
    {
      id: "full-stack",
      ownerId: "paul",
      name: "Full Stack",
      cost: 1,
      kind: "tactic",
      amount: 0,
      fullStackAdded: 1,
      display: {
        value: "+1",
        label: "Work",
        rules: "When target discipline changes this Cycle.",
      },
      rarity: "normal",
      rules: "This Cycle, switching target discipline gives Work +1.",
      tags: ["character", "reward"],
    },
    {
      id: "new-model-dropped",
      ownerId: "paul",
      name: "New Model Dropped",
      cost: 1,
      kind: "tactic",
      amount: 0,
      generatedCards: { cardId: "quick-fix", count: 2 },
      techDebtAdded: 1,
      display: { value: "2", label: "Quick Fixes", rules: "+1 Tech Debt." },
      rarity: "normal",
      rules: "Generate 2 Quick Fixes. Gain 1 Tech Debt.",
      tags: ["character", "reward"],
    },
    {
      id: "post-through-it",
      ownerId: "paul",
      name: "Post Through It",
      cost: 1,
      kind: "tactic",
      amount: 0,
      blockPerCardPlayed: 2,
      display: { value: "×2", label: "Block", rules: "Per prior card today." },
      rarity: "normal",
      rules: "Gain 2 Block per card played before this today.",
      tags: ["character", "defense", "reward"],
    },
    {
      id: "ebb-and-flow",
      ownerId: "paul",
      name: "Ebb & Flow",
      cost: 0,
      kind: "tactic",
      amount: 0,
      focusGained: 3,
      cardsDrawn: 3,
      queuedDistractions: 3,
      exhaust: true,
      display: { value: "+3", label: "Focus", rules: "Draw 3. Next Day: 3 Distractions." },
      rarity: "rare",
      rules: "Gain 3 Focus. Draw 3. Next Day: 3 Distractions. Exhaust.",
      tags: ["character", "exhaust", "rare", "reward"],
    },
  ],
} as const satisfies CharacterContent<"paul">;
