import stephIdle from "../../assets/characters/steph-idle-v1.webp";
import stephSuccess from "../../assets/characters/steph-success-v1.webp";
import stephThinking from "../../assets/characters/steph-thinking-v1.webp";

export const stephContent = {
  developer: {
    id: "steph",
    name: "Steph",
    role: "Toolsmith",
    passiveName: "Paved Road",
    passiveRules: "Whenever a Script or Guard is installed or upgraded, gain 1 Focus for each.",
    startingCardId: "one-click-setup",
    accent: "oklch(0.58 0.18 252)",
    art: {
      idle: stephIdle,
      thinking: stephThinking,
      success: stephSuccess,
    },
  },
  startingCard: {
    id: "one-click-setup",
    ownerId: "steph",
    name: "One-Click Setup",
    cost: 1,
    kind: "tactic",
    amount: 0,
    automation: { kind: "install", power: 1 },
    triggerAutomationAfterInstall: ["script"],
    display: { value: "+1", label: "Script", rules: "Then trigger it." },
    rules: "Install Script 1, then trigger it.",
    tags: ["automation", "character"],
  },
  rewardCards: [
    {
      id: "automate-this-bit",
      ownerId: "steph",
      name: "Automate This Bit",
      cost: 1,
      kind: "tactic",
      amount: 0,
      automation: { kind: "install", power: 2 },
      display: { value: "+2", label: "Script" },
      rarity: "normal",
      rules: "Install Script 2.",
      tags: ["automation", "character", "reward"],
    },
    {
      id: "guardrails-not-gatekeepers",
      ownerId: "steph",
      name: "Guardrails, Not Gatekeepers",
      cost: 1,
      kind: "tactic",
      amount: 0,
      automation: { kind: "install", power: 0, blockPower: 2 },
      triggerAutomationAfterInstall: ["guard"],
      display: { value: "+2", label: "Guard", rules: "Then trigger it." },
      rarity: "normal",
      rules: "Install Guard 2, then trigger it.",
      tags: ["automation", "character", "defense", "reward"],
    },
    {
      id: "refactor-the-workflow",
      ownerId: "steph",
      name: "Refactor the Workflow",
      cost: 1,
      kind: "tactic",
      amount: 0,
      doubleTargetAutomationMeters: true,
      requiresTargetAutomation: true,
      display: { value: "×2", label: "Automation", rules: "Script or squad Guard." },
      rarity: "normal",
      rules: "Double a Script and squad Guard. Aim at the squad to double Guard only.",
      tags: ["automation", "character", "reward"],
    },
    {
      id: "hot-reload",
      ownerId: "steph",
      name: "Hot Reload",
      cost: 1,
      kind: "tactic",
      amount: 0,
      triggerTargetAutomation: { script: true, guard: true, times: 2 },
      display: { value: "×2", label: "Trigger", rules: "Script and squad Guard." },
      rarity: "normal",
      rules: "Trigger a Script and squad Guard twice. Aim at the squad for Guard only.",
      tags: ["automation", "character", "reward"],
    },
    {
      id: "make-it-a-command",
      ownerId: "steph",
      name: "Make It a Command",
      cost: 1,
      kind: "tactic",
      amount: 0,
      generatedCards: { cardId: "macro", count: 2 },
      display: { value: "2", label: "Macros" },
      rarity: "normal",
      rules: "Generate 2 Macros.",
      tags: ["automation", "character", "reward"],
    },
    {
      id: "golden-path",
      ownerId: "steph",
      name: "Golden Path",
      cost: 2,
      kind: "tactic",
      amount: 0,
      scriptPowerPerIncompleteRequirement: 1,
      exhaust: true,
      display: { value: "+1", label: "All Scripts", rules: "Every incomplete bar. Exhaust." },
      rarity: "rare",
      rules: "Install Script 1 on every incomplete requirement. Exhaust.",
      tags: ["automation", "character", "exhaust", "rare", "reward"],
    },
  ],
  generatedCards: [
    {
      id: "macro",
      ownerId: "steph",
      name: "Macro",
      cost: 0,
      kind: "tactic",
      amount: 0,
      triggerTargetAutomation: { script: true, guard: true, times: 1 },
      exhaust: true,
      display: { value: "1×", label: "Trigger", rules: "Script and squad Guard. Exhaust." },
      rules: "Trigger a Script and squad Guard once. Aim at the squad for Guard only. Exhaust.",
      tags: ["automation", "character", "exhaust", "generated"],
    },
  ],
} as const;
