import tobyIdle from "../../assets/characters/toby-idle-v1.webp";
import tobySuccess from "../../assets/characters/toby-success-v1.webp";
import tobyThinking from "../../assets/characters/toby-thinking-v1.webp";

export const tobyContent = {
  developer: {
    id: "toby",
    name: "Toby",
    role: "Operator",
    passiveName: "Quietly On It",
    passiveRules:
      "Crunch damage prevented by Block becomes equal Verified Work on its Task, preferring Infra.",
    startingCardId: "check-the-logs",
    accent: "oklch(0.55 0.13 196)",
    art: {
      idle: tobyIdle,
      thinking: tobyThinking,
      success: tobySuccess,
    },
  },
  startingCard: {
    id: "check-the-logs",
    ownerId: "toby",
    name: "Check the Logs",
    cost: 1,
    kind: "work",
    discipline: "infra",
    amount: 2,
    workKind: "verified",
    block: 3,
    display: { value: "2", label: "Infra", rules: "Verified. Block 3." },
    rules: "Infra 2. Verified. Gain 3 Block.",
    tags: ["character", "defense"],
  },
  rewardCards: [
    {
      id: "on-call",
      ownerId: "toby",
      name: "On Call",
      cost: 1,
      kind: "tactic",
      amount: 0,
      blockEqualIncomingMorale: true,
      display: { value: "ALL", label: "Block", rules: "Match incoming Morale." },
      rarity: "normal",
      rules: "Gain Block equal to the total incoming Morale this Day.",
      tags: ["character", "defense", "reward"],
    },
    {
      id: "useful-alerting",
      ownerId: "toby",
      name: "Useful Alerting",
      cost: 1,
      kind: "tactic",
      amount: 0,
      automation: { kind: "install", power: 0, blockPower: 2 },
      triggerAutomationAfterInstall: ["guard"],
      display: { value: "+2", label: "Guard", rules: "Then trigger it." },
      rarity: "normal",
      rules: "Install Guard 2, then trigger it.",
      tags: ["automation", "character", "defense", "reward"],
    },
    {
      id: "above-and-beyond",
      ownerId: "toby",
      name: "Above and Beyond",
      cost: 0,
      kind: "tactic",
      amount: 0,
      block: 2,
      doubleCurrentBlock: true,
      exhaust: true,
      display: { value: "+2", label: "Block", rules: "Then double it. Exhaust." },
      rarity: "normal",
      rules: "Gain 2 Block, then double your Block. Exhaust.",
      tags: ["character", "defense", "exhaust", "reward"],
    },
    {
      id: "keep-it-humming",
      ownerId: "toby",
      name: "Keep It Humming",
      cost: 1,
      kind: "work",
      discipline: "infra",
      amount: 2,
      workKind: "verified",
      triggerAllTaskGuardsAfterWork: true,
      display: { value: "2", label: "Infra", rules: "Verified. Trigger Task Guards." },
      rarity: "normal",
      rules: "Infra 2. Verified. Trigger every Guard on that Task.",
      tags: ["automation", "character", "reward"],
    },
    {
      id: "triage",
      ownerId: "toby",
      name: "Triage",
      cost: 1,
      kind: "tactic",
      amount: 0,
      block: 4,
      stunIntent: { excludedKinds: ["crunch"] },
      display: { value: "STUN", label: "Intent", rules: "Not Crunch. Block 4." },
      rarity: "normal",
      rules: "Stun one non-Crunch Intent. Gain 4 Block.",
      tags: ["character", "defense", "reward", "stun"],
    },
    {
      id: "nothing-gets-past-me",
      ownerId: "toby",
      name: "Nothing Gets Past Me",
      cost: 1,
      kind: "tactic",
      amount: 0,
      block: 6,
      crunchConversionMode: "all-open-tasks",
      exhaust: true,
      display: { value: "+6", label: "Block", rules: "Crunch converts board-wide." },
      rarity: "rare",
      rules:
        "Gain 6 Block. This Day, prevented Crunch becomes Verified Work on every open Task. Exhaust.",
      tags: ["character", "defense", "exhaust", "rare", "reward"],
    },
  ],
} as const;
